/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as DirectorsRouteImport } from './routes/directors'
import { Route as ActorsRouteImport } from './routes/actors'
import { Route as IndexRouteImport } from './routes/index'

const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorsRoute = DirectorsRouteImport.update({
  id: '/directors',
  path: '/directors',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsRoute = ActorsRouteImport.update({
  id: '/actors',
  path: '/actors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actors': typeof ActorsRoute
  '/directors': typeof DirectorsRoute
  '/movies': typeof MoviesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actors': typeof ActorsRoute
  '/directors': typeof DirectorsRoute
  '/movies': typeof MoviesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actors': typeof ActorsRoute
  '/directors': typeof DirectorsRoute
  '/movies': typeof MoviesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/actors' | '/directors' | '/movies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/actors' | '/directors' | '/movies'
  id: '__root__' | '/' | '/actors' | '/directors' | '/movies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActorsRoute: typeof ActorsRoute
  DirectorsRoute: typeof DirectorsRoute
  MoviesRoute: typeof MoviesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directors': {
      id: '/directors'
      path: '/directors'
      fullPath: '/directors'
      preLoaderRoute: typeof DirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors': {
      id: '/actors'
      path: '/actors'
      fullPath: '/actors'
      preLoaderRoute: typeof ActorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActorsRoute: ActorsRoute,
  DirectorsRoute: DirectorsRoute,
  MoviesRoute: MoviesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
